# Numpy

Arrays and array construction

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3]) # Create a rank 1 array with values 1,2,3

print(type(a), a.shape, a[0], a[1], a[2])

<class 'numpy.ndarray'> (3,) 1 2 3


In [4]:
b = np.array([[1,2], [3,4]]) # Create a rank 2 array
print(b)
print(b.shape)

[[1 2]
 [3 4]]
(2, 2)


In [5]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]]) # Create a 2 x 2 x 2 array
print(c)
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [6]:
a = np.ones(3) # Create an array of all one's. 3 elements.
print(a)

b = np.random.random(3) # Create an array of random numbers in [0,1]. 3 elements.
print(b)

[1. 1. 1.]
[0.73280758 0.40178289 0.93733633]


In [9]:
a = np.zeros((2,2)) # create an array of all zeros. 2 x 2 array
print(a)
print()

b = np.ones((1,2)) # create an array of all zeros. 1 x 2 array
print(b)
print()

c = np.random.random((2,2)) # Create an array filled with random values
print(c)

[[0. 0.]
 [0. 0.]]

[[1. 1.]]

[[0.2036354  0.76881897]
 [0.46135295 0.41347992]]


In [12]:
f = np.arange(10,50,5) # Create an array of values starting at 10, in increments of 5, ending in 50 (less than 50)
print(f)

[10 15 20 25 30 35 40 45]


In [10]:
g = np.linspace(0., 1., num = 5)  # create 5 elements in linear spacing from 0 to 1, inclusive
print(g)

[0.   0.25 0.5  0.75 1.  ]


In [18]:
# Using linspace
linspace_array = np.linspace(0,10,5)
print("Linspace Array:", linspace_array)

# Using arange
arrange_array = np.arange(0,10,2)
print("Arange Array:", arrange_array)

Linspace Array: [ 0.   2.5  5.   7.5 10. ]
Arange Array: [0 2 4 6 8]


In [19]:
a = np.array([[7], [8], [9]])
b = np.array([[4], [5], [6]])
np.hstack((a,b)) # horizontal stack

array([[7, 4],
       [8, 5],
       [9, 6]])

In [20]:
np.vstack((a,b))  # vertical stack

array([[7],
       [8],
       [9],
       [4],
       [5],
       [6]])

# Numpy array attributes

In [21]:
x1 = np.array([5,6,7,8,9])
print(x1.shape)   # (5,)
print(x1)         # [5,6,7,8,9]

(5,)
[5 6 7 8 9]


In [24]:
print("x1 ndim: ", x1.ndim)   # 1
print("x1 ndim: ", x1.shape)  # (5,)

x2 = np.random.random((3,4))  # Two-dimentional array
print("x2 ndim: ", x2.ndim)   # 2
print("x2 shape: ", x2.shape) # (3,4)
print("x2 size: ", x2.size)   # 12

x1 ndim:  1
x1 ndim:  (5,)
x2 ndim:  2
x2 shape:  (3, 4)
x2 size:  12


Datatypes

In [26]:
x = np.array([1,2])                   # Let numpy choose the datatype
y = np.array([1.0, 2.0])              # Let numpy choose the datatype
z = np.array([1,2], dtype = np.int64) # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


# Array indexing: accessing single elements

In [28]:
print(x1)

[5 6 7 8 9]


In [31]:
print(x1[0])
print(x1[4])
print(x1[-1])

5
9
9


In [32]:
print(x2)
print(x2[0,0])
print(x2[2,0])
print(x2[2,-1])
print()
x2[0,0] = 12
print(x2)

[[0.83045496 0.99445755 0.29880081 0.73943605]
 [0.35121364 0.61479676 0.32420693 0.810866  ]
 [0.3288702  0.48945047 0.11103279 0.10178647]]
0.8304549638929969
0.3288702036328157
0.10178646636074828

[[12.          0.99445755  0.29880081  0.73943605]
 [ 0.35121364  0.61479676  0.32420693  0.810866  ]
 [ 0.3288702   0.48945047  0.11103279  0.10178647]]


In [33]:
print(x1)
x1[0] = 3.14519 # this will be truncated!
print(x1)

[5 6 7 8 9]
[3 6 7 8 9]


# Array Slicing: Accessing Subarrays

One-dimensional subarrays

`x[start : stop : step]`

If any of these are unspecified, they default to the values `start=0`, `stop=size of dimension`, `step=1`. 

We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

In [34]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [42]:
print(x[:5])    # first five elements
print(x[5:])    # elements after index 5
print(x[4:7])   # middle sub-array
print(x[::2])   # every other element  # even number
print(x[1::2])  # every other element # odd numbers
print(x[::-1])  # all elements, reversed

[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[4 5 6]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [47]:
# Multi-dimensional subarrays

x2 = np.random.randint(10, size= (3,4)) # Two-dimensional array with random values, each value from [0, 11)
print(x2)

print()
print(x2[:2, :3])  # two rows, three columns

print()
print(x2[:3, ::2]) # all rows, every other column

[[7 1 0 8]
 [0 1 8 6]
 [9 5 9 8]]

[[7 1 0]
 [0 1 8]]

[[7 0]
 [0 8]
 [9 9]]


In [48]:
print(x2[::-1, ::-1]) # reverse row and column

[[8 9 5 9]
 [6 8 1 0]
 [8 0 1 7]]


# Subarrays as no-copy views

In [53]:
print(x2)
print()

x2_sub = x2[:2, :2]
print(x2_sub)
print()

x2_sub[0,0] = 99
print(x2_sub)
print()

print(x2)

[[99  1  0  8]
 [ 0  1  8  6]
 [ 9  5  9  8]]

[[99  1]
 [ 0  1]]

[[99  1]
 [ 0  1]]

[[99  1  0  8]
 [ 0  1  8  6]
 [ 9  5  9  8]]


# Creating copies of arrays

In [56]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)
print()

x2_sub_copy[0,0] = 42
print(x2_sub_copy)
print()

print(x2)

[[99  1]
 [ 0  1]]

[[42  1]
 [ 0  1]]

[[99  1  0  8]
 [ 0  1  8  6]
 [ 9  5  9  8]]


# Reshaping of Arrays

In [65]:
grid = np.arange(1,10).reshape((3,3))
print(grid)
print()

grid = np.arange(1,10)
print(grid)
print()

grid = grid.reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
x = np.array([1,2,3])

# row vector via reshape
print(x.shape)
print(x)
print()

x = x.reshape((3,1))
print(x.shape)
print(x)

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]


In [62]:
x = np.array([1, 2, 3])
# row vector via newaxis

# It adds an axis of length 1 to the array, effectively increasing its dimensionality.
x = x[np.newaxis, :] 

print(x)
print(x.shape)

[[1 2 3]]
(1, 3)


In [63]:
x = np.array([1, 2, 3])

# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [64]:
# column vector via newaxis
x = np.array([1, 2, 3])
x=x[:, np.newaxis]
print(x.shape)

(3, 1)


# Concatenation of arrays

`np.concatenate`, `np.vstack`, `np.hstack`, `np.concatenate`

In [68]:
x = np.array([1,2,3])
y = np.array([3,2,1])
print(np.concatenate([x,y]))

[1 2 3 3 2 1]


In [69]:
z = [99, 99, 99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [70]:
grid = np.array([[1,2,3], 
                 [4,5,6]])

print(grid.shape)

(2, 3)


In [72]:
# concatenate along the first axis (row)
new_grid = np.concatenate([grid, grid], axis=0)
print(new_grid)
print(new_grid.shape)
print()

# concatenate along the second axis (zero-indexed) (column)
new_grid = np.concatenate([grid, grid], axis=1)
print(new_grid)
print(new_grid.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
(4, 3)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
(2, 6)


In [73]:
data = np.array([[1,2], [3,4,],[5,6]])

print(np.max(data))  # Compute max of all elements; prints "6"
print(np.min(data))  # Compute min of all elements; prints "1"
print(np.sum(data))  # Compute sum of all elements; prints "21"

6
1
21
