# Week 2's assignment

**Practice Questions for numpy**
1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
2. Find common elements between A and B. [Hint : Intersection of two sets]
3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [6]:
## Optional Practice Question

#Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

output = []
"""Your code goes here"""

output

[]

# **Question 1**. 

Define two custom numpy arrays, say A and B.

Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [7]:
import numpy as np

In [8]:
# Define two custom numpy arrays A and B
A = np.arange(0,9).reshape(3,3)
print(A)
print()

B = np.arange(5,14).reshape(3,3)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [9]:
# Solution
# stacking A and B vertically
stack_vertical = np.concatenate([A,B], axis = 0)
print("Vertical stack")
print(stack_vertical)
print()

# stacking A and B horizontally
stack_horizontal = np.concatenate([A,B], axis = 1)
print("Horizontal stack")
print(stack_horizontal)

Vertical stack
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]

Horizontal stack
[[ 0  1  2  5  6  7]
 [ 3  4  5  8  9 10]
 [ 6  7  8 11 12 13]]


# **Question 2**. 

Find common elements between A and B. 

[Hint: Intersection of two sets]

In [10]:
# Example 
set_A = set()
set_A.add(1)
set_A.add(2)
set_A.add(3)

set_B = set()
set_B.add(1)
set_B.add(3)
set_B.add(5)

set_intersection = set_A & set_B
print(set_intersection)

# another method: .intersection()
set_intersection_2 = set_A.intersection(set_B)
print(set_intersection_2)

{1, 3}
{1, 3}


In [11]:
# Solution
# flatten arrays
A = np.arange(0,9).reshape(3,3)
A_flatten = A.flatten()
print(A_flatten)

A_set = set(A_flatten)
print(A_set)
print()

B = np.arange(5,14).reshape(3,3)
B_flatten = B.flatten()
print(B_flatten)

B_set = set(B_flatten)
print(B_set)
print()

[0 1 2 3 4 5 6 7 8]
{0, 1, 2, 3, 4, 5, 6, 7, 8}

[ 5  6  7  8  9 10 11 12 13]
{5, 6, 7, 8, 9, 10, 11, 12, 13}



In [12]:
# use A.intersection(B)
intersection_set = A_set.intersection(B_set)
print(f"A has elements: {list(A.flatten())}")
print(f"B has elements: {list(B.flatten())}")
print(f"Intersection: {set(intersection_set)}")

A has elements: [0, 1, 2, 3, 4, 5, 6, 7, 8]
B has elements: [5, 6, 7, 8, 9, 10, 11, 12, 13]
Intersection: {8, 5, 6, 7}


# **Question 3**

Extract all numbers from A which are within a specific range. (e.g. between 5 and 10.)

[Hint: np.where() might be useful or boolean masks]

In [13]:
# example
example_A = np.arange(0,12)
example_A_extract = np.where((example_A > 5) & (example_A < 10))
print(f"Extracted numpy unit: {example_A_extract}")

result_values = example_A[(example_A > 5) & (example_A <10)]
print(f"Values: {result_values}")

Extracted numpy unit: (array([6, 7, 8, 9], dtype=int64),)
Values: [6 7 8 9]


# **Question 4**

Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [14]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [15]:
print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [16]:
print(iris_2d.ndim)
print(iris_2d.dtype)
print(iris_2d.shape)
print(iris_2d[0])
print(iris_2d[0,0])
print(iris_2d[0,:])
print(iris_2d[:,0])

2
float64
(150, 4)
[5.1 3.5 1.4 0.2]
5.1
[5.1 3.5 1.4 0.2]
[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [17]:
print(iris_2d[:,2])

[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
 4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.
 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
 5.7 5.2 5.  5.2 5.4 5.1]


In [18]:
# Filter the rows of iris_2d such that the 1st column has > 5.0
print(iris_2d[iris_2d[:, 0] < 1.5])

[]


In [19]:
# Filter the rows of iris_2d such that the 1st column has > 5.0
print(iris_2d[iris_2d[:, 0] > 5.0])

[[5.1 3.5 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.7 1.5 0.2]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [5.1 3.3 1.7 0.5]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [5.5 3.5 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.8 1.6 0.2]
 [5.3 3.7 1.5 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.

In [20]:
# 3rd column > 1.5 and 1st column < 5
iris_2d[(iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [21]:
# save as an object
iris_2d_filtered = iris_2d[(iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5)]
print(iris_2d_filtered)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


# **Optional Practice Question**

In [22]:
# Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


In [23]:
print(iris)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Ir

In [24]:
print(iris[:, 1].dtype)

object


In [25]:
print(iris[:, 1][:5])

[b'3.5' b'3.0' b'3.2' b'3.1' b'3.6']


In [26]:
print(iris[:,1].astype('float')) #sepal width

[3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
 3.5 3.1 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
 2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
 2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
 2.6 3.  2.6 2.3 2.7 3.  2.9 2.9 2.5 2.8 3.3 2.7 3.  2.9 3.  3.  2.5 2.9
 2.5 3.6 3.2 2.7 3.  2.5 2.8 3.2 3.  3.8 2.6 2.2 3.2 2.8 2.8 2.7 3.3 3.2
 2.8 3.  2.8 3.  2.8 3.8 2.8 2.8 2.6 3.  3.4 3.1 3.  3.1 3.1 3.1 2.7 3.2
 3.3 3.  2.5 3.  3.4 3. ]


In [27]:
numeric_column = iris[:, 1].astype('float') # sepal width
grouping_column = iris[:, 4]                # species

In [28]:
print(numeric_column[:5])
print(grouping_column[:5])
print(grouping_column.dtype)

[3.5 3.  3.2 3.1 3.6]
[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']
object


In [29]:
#Find the mean of a numeric column grouped by a categorical column in a 2D numpy array
numeric_column = iris[:, 1].astype('float') # sepal width
grouping_column = iris[:, 4]                # species

In [30]:
grouping_column = grouping_column.astype(str)
print(grouping_column.dtype)
print(grouping_column[:5])

unique_groups = np.unique(grouping_column)
print(unique_groups)

<U15
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [31]:
array_setosa = []
array_versicolor = []
array_virginica = []

In [32]:
for index in range(len(grouping_column)):
    if grouping_column[index] == "Iris-setosa":
        array_setosa.append(numeric_column[index])
    elif grouping_column[index] == "Iris-versicolor":
        array_versicolor.append(numeric_column[index])
    elif grouping_column[index] == "Iris-virginica":
        array_virginica.append(numeric_column[index])

In [33]:
print(np.mean(array_setosa))
print(f"Mean of Iris-setosa: {np.mean(array_setosa)}")
print(f"Mean of Iris-versicolor: {np.mean(array_versicolor)}")
print(f"Mean of Iris-virginica: {np.mean(array_virginica)}")

3.418
Mean of Iris-setosa: 3.418
Mean of Iris-versicolor: 2.7700000000000005
Mean of Iris-virginica: 2.974


In [34]:
output = []

output.append(np.mean(array_setosa))
output.append(np.mean(array_versicolor))
output.append(np.mean(array_virginica))

print(output)

[3.418, 2.7700000000000005, 2.974]


In [37]:
# final solution
# Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

numeric_column = iris[:, 1].astype('float') # sepal width
grouping_column = iris[:, 4]                # species

grouping_column = grouping_column.astype(str)
unique_groups = np.unique(grouping_column)

array_setosa = []
array_versicolor = []
array_virginica = []

for index in range(len(grouping_column)):
    if grouping_column[index] == "Iris-setosa":
        array_setosa.append(numeric_column[index])
    elif grouping_column[index] == "Iris-versicolor":
        array_versicolor.append(numeric_column[index])
    elif grouping_column[index] == "Iris-virginica":
        array_virginica.append(numeric_column[index])


output = []

output.append(np.mean(array_setosa))
output.append(np.mean(array_versicolor))
output.append(np.mean(array_virginica))

print(f"output: {output}")

output: [3.418, 2.7700000000000005, 2.974]
